library(flowCore)
fcs.path <-list.dirs("~/data/FCS/",recursive = F)
fcs.path <-setdiff(fcs.path,c("/home/rstudio/data/FCS//Not_used",
                              "/home/rstudio/data/FCS//Wheatley",
                              "/home/rstudio/data/FCS//NKI"))
grbg <- lapply( fcs.path, function(i)
{
  print(i)
  files <- list.files(i,full.names = T,pattern = ".fcs|.LMD")
  f <- read.FCS(filename = files[1],emptyValue = FALSE)
  markers <- as.vector(f@parameters@data[,2])
  chans <- colnames(f)
  
  if (all(is.na(markers)))
  {
    counter <-2
    while(all(is.na(markers)))
    {
      f <- read.FCS(filename = files[counter])
      markers <- as.vector(f@parameters@data[,2])
      counter <- sample(3:length(files),size = 1)
    }
  }
  markers <- unlist(lapply(markers, function(x) unlist(strsplit(x," "))[1]))
  ind<-grep(markers, pattern = "Live|LIVE|VITALITY|VIABILITY|LIVE*|viability",fixed = F,ignore.case = F)
  if(length(ind)==1)
    markers[ind]<-"Live"
  to.remove<-grep(chans, pattern = "-H|-W|FSC-A|FSC-H|Time|TIME|time|FS|FSC-W|SSC-B")
  if(length(to.remove)<length(chans)){
    markers <- markers[-to.remove]
    chans <- chans[-to.remove]
    
  }else{
    to.remove<-grep(chans, pattern = "-W|FSC-A|FSC-H|Time|Width")
    if(length(to.remove)<length(chans)){
      markers <- markers[-to.remove]
      chans <- chans[-to.remove]
    }
  }
     na.inds <- which(is.na(markers))
     if (length(na.inds)>0)
       markers[na.inds]<-chans[na.inds]
    write.table(cbind(markers, chans,deparse.level = F),
                file =paste0("~/data/Metadata/Markers_info/",basename(i),"_MarkersChannels.csv" ),
                row.names = F,col.names = c("Markers","channels"),sep=",")
  return(length(files))

  })


#Had to manually fix some of the marker files, to make sure markers are same
##Now finding the marker combination and counting
markers.list <- write.table(matrix(c("-","-","-"),nrow = 1,ncol = 3,byrow = T),
                          col.names = c("Marker pair","number of samples","Projects"),
                          row.names = F, sep = ",",
                          file = "~/data/Metadata/MarkerPairs.csv")
marker.path <-list.files("~/data/Metadata/Markers_info/",pattern=".csv",full.names = T)
pair.path <- list.files("~/data/Metadata/Project_markersComb/",pattern=".csv",full.names = T)
names(pair.path) <-unlist(lapply(pair.path, function(x) 
   unlist(strsplit(basename(x),"_pairs"))[1]))
names(marker.path) <- unlist(lapply(marker.path, function(x) 
      unlist(strsplit(basename(x),"_Marker"))[1]))
all.pairs <- sapply(names(pair.path),function(n1){
  pair.mat<- as.matrix(read.table(pair.path[n1],sep=",",check.names = F, header=T))
  marker.mat<- read.csv(marker.path[n1],check.names = F, fileEncoding = "UTF-7",header=T)
  match.markers <- apply(pair.mat,1, function(p1) 
    paste(as.vector(marker.mat[,1])[match(p1, as.vector(marker.mat[,2]))],collapse="_"))
  return(cbind(match.markers,n1))
  
})
all.pairs <- do.call(rbind,all.pairs)
markers.bank <- data.frame(pairs=unique(all.pairs[,1]),filecount=0,project=NA,projectcount=0)
file.info <- read.table("~/data/Metadata/file_info.csv",sep=",",header=T,check.names = F)
for ( i in 1:nrow(all.pairs))
{
  ind <- match(all.pairs[i,1], markers.bank[,1])
  markers.bank$filecount[ind] <- markers.bank$filecount[ind]+file.info[which(file.info[,1]==all.pairs[i,2]),2]
  markers.bank$project[ind] <- paste(
    ifelse(is.na(markers.bank$project[ind]),yes = "",no =markers.bank$project[ind]),
    all.pairs[i,2],sep="&")
  markers.bank$projectcount[ind] <- markers.bank$projectcount[ind]+1
  
  
  }
  
  #Read the corresponding file from "~/data/Metadata/Project_markersComb/", and
  #match pairs to markers and add number of fcs files
  #You probably need to create the csv file, cause you need to read it in each lapply and add it
  #to the information that might be there already, i.e. CD3CD4 is already generated by COP and OneStudy
}
