######## import code flowTypeFilter,libraries and functions ######
install.packages("/home/rstudio/Code_Bcells_Myeloid_cells/flowTypeFilter_code/flowTypeFilterC_1.0_R_x86_64-pc-linux-gnu.tar.gz",repos=NULL, type="source")
library(flowCore)
library(stringr)
library(data.table)
library(flowTypeFilterC)
library(parallel)
source("/home/rstudio/Code_Bcells_Myeloid_cells/Utils_flowType_analysis.R")
source("/home/rstudio/Code_Bcells_Myeloid_cells/Execution_flowType.R")

#########################################################################################################################
################# execute functions #####################################################################################
#########################################################################################################################
# I read all fcs files of folder as a flowSet
fs_Bcells<-import_fs("/home/rstudio/data/flowType_data/Bcell_panel/Batch_1/batch_1/fcs_files")
fs_myeloid<-import_fs("/home/rstudio/data/flowType_data/Myeloid_panel/Batch_4/Plate_5/fcs_files")
length(fs_Bcells)
length(fs_myeloid)
# I change fs_Bcells or fs_myeloid everytime I execute the function on a different set of fcs file (fcs file of each plate)
# the fcs files are stored on the bioinformatic server

############################## Bcell panel ################################
# execute_flowType_filter() is the main function that takes as input a flowSet objects.
# path_df_thresholds is the directory containing the the csv file with the thresholds found by flowDensity for each sample
# path_filter_object is the directory containing the filter objects. Each filter object is a list of the filter matrix for each sample
# path_output where to store the result. The result is a csv file containing the number of cells for each population generated by the flowTypeFilter.
# Note: The original data is organized in batches and plates, the function was executed separately for each plate of the experiment (to reduce the load on memory and to check the results better)
# if the user wants  to execute on everything, you just need to combine the df_thresholds 
# and each df filters in one file. Then put the fcs files in one folder. 
# The total time is just the sum of all the times calculated for each plate.
# Note: Remember to separate the Bcell panel analysis from the the Myeloid panel analysis
path_thr<-"/home/rstudio/data/flowType_data/Bcell_panel/Batch_1/batch_1/df_thresholds"
path_filter<- "/home/rstudio/data/flowType_data/Bcell_panel/Batch_1/batch_1/filter_objects"
df_flowType_results<-execute_flowType_filter(fs_Bcells,path_df_thresholds = path_thr,
                                             path_filter_objects = path_filter,
                                             path_output ="/home/rstudio/results/flowType_results/df_flowType_results.csv", panel = "Bcells")


############################# Myeloid panel #######################################################
path_thr<-"/home/rstudio/data/flowType_data/Myeloid_panel/Batch_4/Plate_5/df_thresholds"
path_filter<- "/home/rstudio/data/flowType_data/Myeloid_panel/Batch_4/Plate_5/filter_objects"

df_flowType_results<-execute_flowType_filter(fs_myeloid,path_df_thresholds =path_thr,
                                             path_filter_objects = path_filter,
                                             path_output ="/home/rstudio/results/flowType_results/df_flowType_results.csv", panel = "myeloid",n_cores = 10)

################# combine all dfs ###################
# the function combine_all_flowtype_dfs combines the flow_type_results of each plate  in one file
paths_all_flowType_results_Bcells<-list.files("/home/rstudio/data/flowType_results_all_batches_Bcells/",recursive = T,full.names = T)
paths_all_flowType_results_myeloid<-list.files("/home/rstudio/data/flowType_results_all_batches_myeloid/",recursive = T,full.names = T)

final_flowtyperesults_df_bcells<-combine_all_flowtype_dfs(paths_all_flowType_results_Bcells,
                                                                               type_data="All",type_visit="All",n_cores=17,
                                                                               path_samples_info = "/home/rstudio/data/Samples_info_plates_all_batches_complete.csv")
final_flowtyperesults_df_myeloid<-combine_all_flowtype_dfs(paths_all_flowType_results_myeloid,
                                                                                type_data = "All",type_visit = "All",n_cores = 17,
                                                                                path_samples_info = "/home/rstudio/data/Samples_info_plates_all_batches_complete.csv") 
#------------- check df
vec<-unique(final_flowtyperesults_df_myeloid$samples_name)

vec<-unique(final_flowtyperesults_df_bcells$samples_name)

#------------ write the selected flow type df
write.csv(final_flowtyperesults_df_bcells,"/home/rstudio/data/flowType_results_final/final_flowtyperesults_df_bcells.csv",row.names = F)

write.csv(final_flowtyperesults_df_myeloid,"/home/rstudio/data/flowType_results_final/final_flowtyperesults_df_myeloid.csv",row.names = F)

# once we have the proportions of each pop for each sample(using flowType),we find the samples that are positive or negative to the vaccine response (using the info in the AWS).
# Take all the pop x of samples with positive response,the pop x of samples with negative,we test if the mean is different.
# and so on for the other populations. # in the end we will have a correlation score for each phenotype. We will use Rhychptomix for the final plot.

###################### flowtype data for ML analysis  ######################
# data to put in the ML version folder in local, Rdata/FlowType_data folder on AWS
final_flowtyperesults_df_bcells<-combine_all_flowtype_dfs(paths_all_flowType_results_Bcells,type_data="All",type_visit="All",n_cores=1)

final_flowtyperesults_df_myeloid<-combine_all_flowtype_dfs(paths_all_flowType_results_myeloid,type_data = "All",type_visit = "All",n_cores = 1)

# Convert to ML like shape

final_flowtyperesults_df_bcells_reshaped<-dcast(final_flowtyperesults_df_bcells,samples_name ~ phenotype_names,value.var="cell_counts")
final_flowtyperesults_df_bcells_reshaped[,2:length(colnames(final_flowtyperesults_df_bcells_reshaped)) ] <- lapply(final_flowtyperesults_df_bcells_reshaped[, 2:length(colnames(final_flowtyperesults_df_bcells_reshaped))], as.numeric)
#sapply(final_flowtyperesults_df_bcells_reshaped,class)
final_flowtyperesults_df_myeloid_reshaped<-dcast(final_flowtyperesults_df_myeloid,samples_name ~ phenotype_names,value.var="cell_counts")
final_flowtyperesults_df_myeloid_reshaped[,2:length(colnames(final_flowtyperesults_df_myeloid_reshaped)) ] <- lapply(final_flowtyperesults_df_myeloid_reshaped[, 2:length(colnames(final_flowtyperesults_df_myeloid_reshaped))], as.numeric)

# generate the frequencies on live cells version
ind<-grep("live",colnames(final_flowtyperesults_df_bcells_reshaped))
live_counts<-final_flowtyperesults_df_bcells_reshaped[,ind]
final_flowtyperesults_df_bcells_reshaped_freqs<-final_flowtyperesults_df_bcells_reshaped
final_flowtyperesults_df_bcells_reshaped_freqs[,2:length(colnames(final_flowtyperesults_df_bcells_reshaped_freqs))]<-format(round(final_flowtyperesults_df_bcells_reshaped_freqs[,2:length(colnames(final_flowtyperesults_df_bcells_reshaped_freqs))]/live_counts,3),scientific=F)
final_flowtyperesults_df_bcells_reshaped_freqs[,1:10]

ind<-grep("live",colnames(final_flowtyperesults_df_myeloid_reshaped))
live_counts<-final_flowtyperesults_df_myeloid_reshaped[,ind]
final_flowtyperesults_df_myeloid_reshaped_freqs<-final_flowtyperesults_df_myeloid_reshaped
final_flowtyperesults_df_myeloid_reshaped_freqs[,2:length(colnames(final_flowtyperesults_df_myeloid_reshaped_freqs))]<-format(round(final_flowtyperesults_df_myeloid_reshaped_freqs[,2:length(colnames(final_flowtyperesults_df_myeloid_reshaped_freqs))]/live_counts,3),scientific=F)
final_flowtyperesults_df_myeloid_reshaped_freqs[,1:10]

# check ID
nrow(final_flowtyperesults_df_bcells_reshaped)
ncol(final_flowtyperesults_df_bcells_reshaped)

nrow(final_flowtyperesults_df_myeloid_reshaped)
ncol(final_flowtyperesults_df_myeloid_reshaped)

nrow(final_flowtyperesults_df_bcells_reshaped_freqs)
ncol(final_flowtyperesults_df_bcells_reshaped_freqs)

nrow(final_flowtyperesults_df_myeloid_reshaped_freqs)
ncol(final_flowtyperesults_df_myeloid_reshaped_freqs)

# write df
write.csv(final_flowtyperesults_df_bcells_reshaped,"/home/rstudio/data/flowType_results_final/ML_version_data/final_flowtyperesults_df_bcells.csv",row.names = F)
write.csv(final_flowtyperesults_df_bcells_reshaped_freqs,"/home/rstudio/data/flowType_results_final/ML_version_data/final_flowtyperesults_df_bcells_freqs.csv",row.names = F)

write.csv(final_flowtyperesults_df_myeloid_reshaped,"/home/rstudio/data/flowType_results_final/ML_version_data/final_flowtyperesults_df_myeloid.csv",row.names = F)
write.csv(final_flowtyperesults_df_myeloid_reshaped_freqs,"/home/rstudio/data/flowType_results_final/ML_version_data/final_flowtyperesults_df_myeloid_freqs.csv",row.names = F)

# test csv file

df_test_1<-read.csv(file="/home/rstudio/results/flowType_results/final_flowtyperesults_df_bcells_reshaped.csv")
df_test_2<-read.csv("/home/rstudio/results/flowType_results/final_flowtyperesults_df_myeloid_reshaped.csv")

nrow(df_test_1)
nrow(df_test_2)
